language: generic

sudo: required
services:
  - docker
before_install:
  - docker build -t ajosemalik/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ajosemalik/docker-react npm run test -- --coverage