language: generic

sudo: required
services:
  - docker
before_install:
  - docker build -t ajosemalik/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ajosemalik/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'ma-docker-react'
  env: 'Madockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-357253837123'
  bucket_path: 'ma-docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"